apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: granite4-7b-tiny-amd-r4-tp1
  namespace: vinod
spec:
  model:
    uri: hf://ibm-granite/granite-4.0-h-tiny
    name: ibm-granite/granite-4.0-h-tiny
  replicas: 4
  router:
    route: { }
    gateway: { }
    scheduler: { }
  template:
    containers:
      - name: main
        image: ghcr.io/llm-d/llm-d-rocm:v0.6.0
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: "--tensor-parallel-size 1"
        resources:
          limits:
            cpu: "8"
            memory: 64Gi
            amd.com/gpu: "1"
          requests:
            cpu: "4"
            memory: 32Gi
            amd.com/gpu: "1"
