apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector-varun
  namespace: varun-benchmark
  labels:
    benchmark.ibm/owner: varun
spec:
  containers:
  - name: inspector
    image: registry.access.redhat.com/ubi8/ubi
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: results-storage
      mountPath: /mnt/results
  volumes:
  - name: results-storage
    persistentVolumeClaim:
      claimName: guidellm-results-pvc-varun
